import {
  camelCase,
  pascalCase,
  slugify,
  type GeneratedFile,
  type ModelDef,
  type ProjectConfig,
  type TreeNode,
} from "./types";

const has = (c: ProjectConfig, id: string) =>
  c.modules.includes(id as ProjectConfig["modules"][number]);

const pad = (value: string, width: number) => value.padEnd(width, " ");

function renderModel(model: ModelDef): string {
  const name = pascalCase(model.name);
  const rows = [
    { key: "id", type: "String", attrs: "@id @default(cuid())" },
    ...model.fields.map((f) => ({
      key: camelCase(f.name),
      type: `${f.type}${f.list ? "[]" : ""}${f.optional && !f.list ? "?" : ""}`,
      attrs: [
        f.unique ? "@unique" : "",
        f.name === "createdAt" ? "@default(now())" : "",
        f.name === "updatedAt" ? "@updatedAt" : "",
      ]
        .filter(Boolean)
        .join(" "),
    })),
    { key: "updatedAt", type: "DateTime", attrs: "@updatedAt" },
  ];
  const keyWidth = Math.max(...rows.map((r) => r.key.length)) + 1;
  const typeWidth = Math.max(...rows.map((r) => r.type.length)) + 1;
  const body = rows
    .map(
      (r) =>
        `  ${pad(r.key, keyWidth)}${pad(r.type, typeWidth)}${r.attrs}`.trimEnd(),
    )
    .join("\n");
  return `model ${name} {\n${body}\n\n  @@map("${camelCase(name)}s")\n}`;
}

function prismaSchema(c: ProjectConfig): string {
  const models = c.models.map(renderModel).join("\n\n");
  const session = has(c, "auth")
    ? `\n\nmodel Session {\n  id        String   @id @default(cuid())\n  token     String   @unique\n  userId    String\n  expiresAt DateTime\n  createdAt DateTime @default(now())\n\n  @@index([userId])\n  @@map("sessions")\n}`
    : "";
  return `// Generated by Forge — edit freely, this is your code.
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${models}${session}
`;
}

function packageJson(c: ProjectConfig): string {
  const pm = c.packageManager;
  const deps: Record<string, string> = {
    "@prisma/client": "^6.2.1",
    next: "^16.0.0",
    react: "^19.2.0",
    "react-dom": "^19.2.0",
    zod: "^3.24.2",
  };
  if (has(c, "auth")) deps["bcryptjs"] = "^2.4.3";
  if (has(c, "billing")) deps["stripe"] = "^17.5.0";

  const devDeps: Record<string, string> = {
    "@types/node": "^22.10.0",
    "@types/react": "^19.2.0",
    "@types/react-dom": "^19.2.0",
    eslint: "^9.17.0",
    "eslint-config-next": "^16.0.0",
    prisma: "^6.2.1",
    typescript: "^5.7.0",
  };
  if (has(c, "auth")) devDeps["@types/bcryptjs"] = "^2.4.6";
  if (has(c, "testing")) {
    devDeps["vitest"] = "^2.1.8";
    devDeps["@vitejs/plugin-react"] = "^4.3.4";
  }

  const scripts: Record<string, string> = {
    dev: "next dev",
    build: "prisma generate && next build",
    start: "next start",
    lint: "next lint",
    typecheck: "tsc --noEmit",
    "db:migrate": "prisma migrate dev",
    "db:deploy": "prisma migrate deploy",
    "db:studio": "prisma studio",
    "db:seed": `${pm === "npm" ? "tsx" : "tsx"} prisma/seed.ts`,
  };
  if (has(c, "testing")) scripts["test"] = "vitest run";

  return `${JSON.stringify(
    {
      name: slugify(c.name),
      version: "0.1.0",
      private: true,
      engines: { node: `>=${c.nodeVersion}` },
      scripts,
      dependencies: deps,
      devDependencies: devDeps,
      prisma: { seed: "tsx prisma/seed.ts" },
    },
    null,
    2,
  )}\n`;
}

function dockerfile(c: ProjectConfig): string {
  return `# syntax=docker/dockerfile:1.7
# Multi-stage build: small, non-root, reproducible.

FROM node:${c.nodeVersion}-alpine AS base
RUN apk add --no-cache libc6-compat
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npx prisma generate
RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN addgroup --system --gid 1001 nodejs \\
 && adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
USER nextjs
EXPOSE ${c.port}
ENV PORT=${c.port}
HEALTHCHECK --interval=30s --timeout=3s --retries=3 \\
  CMD wget -qO- http://127.0.0.1:${c.port}/api/health || exit 1
CMD ["node", "server.js"]
`;
}

function compose(c: ProjectConfig): string {
  const name = slugify(c.name);
  return `services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${c.port}:${c.port}"
    environment:
      DATABASE_URL: postgresql://postgres:\${POSTGRES_PASSWORD:-postgres}@db:5432/${name}?schema=public
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node server.js"

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${name}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${name}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
`;
}

function envExample(c: ProjectConfig): string {
  const lines = [
    `# Copy to .env.local for local dev. Never commit real secrets.`,
    `DATABASE_URL="postgresql://postgres:postgres@localhost:5432/${slugify(c.name)}?schema=public"`,
    `POSTGRES_PASSWORD="postgres"`,
    `PORT="${c.port}"`,
  ];
  if (has(c, "auth")) {
    lines.push(`AUTH_SECRET="replace-with-openssl-rand-base64-32"`);
    lines.push(`SESSION_COOKIE_NAME="${slugify(c.name)}_session"`);
  }
  if (has(c, "billing")) {
    lines.push(`STRIPE_SECRET_KEY="sk_test_..."`);
    lines.push(`STRIPE_WEBHOOK_SECRET="whsec_..."`);
  }
  return `${lines.join("\n")}\n`;
}

function dbClient(): string {
  return `import { PrismaClient } from "@prisma/client";

// A single client instance survives hot reloads in development.
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["query", "warn", "error"] : ["error"],
  });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
`;
}

function envModule(c: ProjectConfig): string {
  const extra = [
    has(c, "auth") ? `  AUTH_SECRET: z.string().min(32),` : "",
    has(c, "billing")
      ? `  STRIPE_SECRET_KEY: z.string().startsWith("sk_"),\n  STRIPE_WEBHOOK_SECRET: z.string().startsWith("whsec_"),`
      : "",
  ]
    .filter(Boolean)
    .join("\n");
  return `import { z } from "zod";

// Fail fast at boot instead of at 3am in production.
const schema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  DATABASE_URL: z.string().url(),
${extra}
});

export const env = schema.parse(process.env);
`;
}

function seed(c: ProjectConfig): string {
  const first = c.models[0];
  const body = first
    ? `  await prisma.${camelCase(pascalCase(first.name))}.createMany({
    data: [
${first.fields
  .slice(0, 3)
  .map(
    (f) =>
      `      // ${camelCase(f.name)}: ${
        f.type === "String" ? `"example"` : f.type === "Boolean" ? "true" : "0"
      },`,
  )
  .join("\n")}
    ],
    skipDuplicates: true,
  });`
    : "  // Add seed data here.";
  return `import { prisma } from "../src/lib/db";

async function main() {
${body}
}

main()
  .then(() => console.log("Seed complete"))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
`;
}

function layoutTsx(c: ProjectConfig): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${c.name}",
  description: "${c.description.replace(/"/g, '\\"')}",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function pageTsx(c: ProjectConfig): string {
  const first = c.models[0];
  const model = first ? camelCase(pascalCase(first.name)) : null;
  return `import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function HomePage() {
${
  model
    ? `  const rows = await prisma.${model}.findMany({ take: 20, orderBy: { createdAt: "desc" } });`
    : "  const rows: unknown[] = [];"
}

  return (
    <main>
      <h1>${c.name}</h1>
      <p>${c.description.replace(/</g, "&lt;")}</p>
      <p>{rows.length} record(s) loaded from Postgres via Prisma.</p>
    </main>
  );
}
`;
}

function healthRoute(): string {
  return `import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export async function GET() {
  try {
    await prisma.$queryRaw\`SELECT 1\`;
    return Response.json({ status: "ok", db: "up" });
  } catch {
    return Response.json({ status: "degraded", db: "down" }, { status: 503 });
  }
}
`;
}

function authModule(c: ProjectConfig): string {
  return `import { cookies } from "next/headers";
import bcrypt from "bcryptjs";
import { randomBytes } from "node:crypto";
import { prisma } from "./db";
import { env } from "./env";

const COOKIE = process.env.SESSION_COOKIE_NAME ?? "${slugify(c.name)}_session";
const TTL_MS = 1000 * 60 * 60 * 24 * 7;

export const hashPassword = (plain: string) => bcrypt.hash(plain, 12);
export const verifyPassword = (plain: string, hash: string) =>
  bcrypt.compare(plain, hash);

export async function createSession(userId: string) {
  const token = randomBytes(32).toString("hex");
  await prisma.session.create({
    data: { token, userId, expiresAt: new Date(Date.now() + TTL_MS) },
  });
  const store = await cookies();
  store.set(COOKIE, token, {
    httpOnly: true,
    sameSite: "lax",
    secure: env.NODE_ENV === "production",
    path: "/",
    maxAge: TTL_MS / 1000,
  });
}

export async function getSessionUserId(): Promise<string | null> {
  const token = (await cookies()).get(COOKIE)?.value;
  if (!token) return null;
  const session = await prisma.session.findUnique({ where: { token } });
  if (!session || session.expiresAt < new Date()) return null;
  return session.userId;
}

export async function destroySession() {
  const store = await cookies();
  const token = store.get(COOKIE)?.value;
  if (token) await prisma.session.deleteMany({ where: { token } });
  store.delete(COOKIE);
}
`;
}

function middlewareTs(): string {
  return `import { NextResponse, type NextRequest } from "next/server";

const PROTECTED = ["/dashboard"];

export function middleware(request: NextRequest) {
  const needsAuth = PROTECTED.some((p) => request.nextUrl.pathname.startsWith(p));
  const hasSession = Boolean(request.cookies.get(process.env.SESSION_COOKIE_NAME ?? "session"));
  if (needsAuth && !hasSession) {
    const url = request.nextUrl.clone();
    url.pathname = "/login";
    return NextResponse.redirect(url);
  }
  return NextResponse.next();
}

export const config = { matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"] };
`;
}

function stripeWebhook(): string {
  return `import Stripe from "stripe";
import { env } from "@/lib/env";

const stripe = new Stripe(env.STRIPE_SECRET_KEY);

// Signature verification must happen on the raw body, before any parsing.
export async function POST(request: Request) {
  const signature = request.headers.get("stripe-signature");
  const body = await request.text();
  if (!signature) return new Response("Missing signature", { status: 400 });

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(body, signature, env.STRIPE_WEBHOOK_SECRET);
  } catch {
    return new Response("Invalid signature", { status: 400 });
  }

  switch (event.type) {
    case "checkout.session.completed":
      // fulfil the order
      break;
    default:
      break;
  }

  return Response.json({ received: true });
}
`;
}

function ciWorkflow(c: ProjectConfig): string {
  return `name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ${slugify(c.name)}
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=5s
          --health-timeout=5s --health-retries=10
        ports: ["5432:5432"]
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/${slugify(c.name)}?schema=public
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "${c.nodeVersion}"
          cache: npm
      - run: npm ci
      - run: npx prisma migrate deploy
      - run: npm run typecheck
      - run: npm run lint
${has(c, "testing") ? "      - run: npm test\n" : ""}      - run: docker build -t ${slugify(c.name)}:ci .
`;
}

function readme(c: ProjectConfig): string {
  return `# ${c.name}

${c.description}

## Stack

- Next.js 16 (App Router) + React 19
- Prisma ORM + PostgreSQL 17
- Docker + Docker Compose${has(c, "auth") ? "\n- Cookie sessions with bcrypt hashing" : ""}${has(c, "billing") ? "\n- Stripe checkout + verified webhooks" : ""}${has(c, "cicd") ? "\n- GitHub Actions CI" : ""}

## Run with Docker

\`\`\`bash
cp .env.example .env
docker compose up --build
\`\`\`

The app is served on http://localhost:${c.port} and migrations are applied on boot.

## Run locally

\`\`\`bash
${c.packageManager} install
${c.packageManager} run db:migrate
${c.packageManager} run dev
\`\`\`

## Conventions

- Environment variables are validated once in \`src/lib/env.ts\`; the process refuses to boot on a bad config.
- The Prisma client is a singleton in \`src/lib/db.ts\` to survive hot reloads.
- \`/api/health\` reports database reachability and backs the container healthcheck.
`;
}

function nextConfig(): string {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Emits a minimal server bundle for the Docker runner stage.
  output: "standalone",
  reactStrictMode: true,
  poweredByHeader: false,
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-Frame-Options", value: "DENY" },
        ],
      },
    ];
  },
};

export default nextConfig;
`;
}

export function generateFiles(c: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [
    { path: "README.md", contents: readme(c), language: "md" },
    { path: "package.json", contents: packageJson(c), language: "json" },
    { path: "next.config.ts", contents: nextConfig(), language: "ts" },
    {
      path: "tsconfig.json",
      contents: `${JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            lib: ["dom", "dom.iterable", "esnext"],
            strict: true,
            noUncheckedIndexedAccess: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            jsx: "preserve",
            incremental: true,
            plugins: [{ name: "next" }],
            paths: { "@/*": ["./src/*"] },
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"],
        },
        null,
        2,
      )}\n`,
      language: "json",
    },
    { path: ".env.example", contents: envExample(c), language: "env" },
    {
      path: ".gitignore",
      contents: `node_modules\n.next\n.env\n.env.local\ndist\ncoverage\n`,
      language: "text",
    },
    {
      path: "prisma/schema.prisma",
      contents: prismaSchema(c),
      language: "prisma",
    },
    { path: "prisma/seed.ts", contents: seed(c), language: "ts" },
    { path: "src/lib/db.ts", contents: dbClient(), language: "ts" },
    { path: "src/lib/env.ts", contents: envModule(c), language: "ts" },
    { path: "src/app/layout.tsx", contents: layoutTsx(c), language: "ts" },
    { path: "src/app/page.tsx", contents: pageTsx(c), language: "ts" },
    {
      path: "src/app/globals.css",
      contents: `:root { color-scheme: light dark; }\nbody { margin: 0; font-family: system-ui, sans-serif; }\n`,
      language: "text",
    },
    {
      path: "src/app/api/health/route.ts",
      contents: healthRoute(),
      language: "ts",
    },
  ];

  if (has(c, "docker")) {
    files.push(
      { path: "Dockerfile", contents: dockerfile(c), language: "docker" },
      { path: "docker-compose.yml", contents: compose(c), language: "yaml" },
      {
        path: ".dockerignore",
        contents: `node_modules\n.next\n.git\n.env*\nDockerfile\ndocker-compose.yml\n`,
        language: "text",
      },
    );
  }

  if (has(c, "auth")) {
    files.push(
      { path: "src/lib/auth.ts", contents: authModule(c), language: "ts" },
      { path: "src/middleware.ts", contents: middlewareTs(), language: "ts" },
    );
  }

  if (has(c, "billing")) {
    files.push({
      path: "src/app/api/stripe/webhook/route.ts",
      contents: stripeWebhook(),
      language: "ts",
    });
  }

  if (has(c, "cicd")) {
    files.push({
      path: ".github/workflows/ci.yml",
      contents: ciWorkflow(c),
      language: "yaml",
    });
  }

  if (has(c, "testing")) {
    files.push(
      {
        path: "vitest.config.ts",
        contents: `import { defineConfig } from "vitest/config";\n\nexport default defineConfig({\n  test: { environment: "node", include: ["tests/**/*.test.ts"] },\n});\n`,
        language: "ts",
      },
      {
        path: "tests/health.test.ts",
        contents: `import { describe, expect, it } from "vitest";\n\ndescribe("health contract", () => {\n  it("reports a status field", () => {\n    expect({ status: "ok" }).toHaveProperty("status");\n  });\n});\n`,
        language: "ts",
      },
    );
  }

  return files.sort((a, b) => a.path.localeCompare(b.path));
}

export function buildTree(files: GeneratedFile[]): TreeNode[] {
  const root: TreeNode[] = [];

  for (const file of files) {
    const segments = file.path.split("/");
    let level = root;
    let prefix = "";
    segments.forEach((segment, index) => {
      prefix = prefix ? `${prefix}/${segment}` : segment;
      const isFile = index === segments.length - 1;
      let node = level.find((n) => n.name === segment && n.path === prefix);
      if (!node) {
        node = {
          name: segment,
          path: prefix,
          kind: isFile ? "file" : "dir",
          ...(isFile ? {} : { children: [] }),
        };
        level.push(node);
      }
      if (!isFile) level = node.children!;
    });
  }

  const sort = (nodes: TreeNode[]): TreeNode[] =>
    nodes
      .map((n) => (n.children ? { ...n, children: sort(n.children) } : n))
      .sort((a, b) =>
        a.kind === b.kind
          ? a.name.localeCompare(b.name)
          : a.kind === "dir"
            ? -1
            : 1,
      );

  return sort(root);
}

export interface Issue {
  level: "error" | "warning";
  message: string;
}

export function validateConfig(c: ProjectConfig): Issue[] {
  const issues: Issue[] = [];
  if (!c.name.trim()) issues.push({ level: "error", message: "Project name is required" });
  if (c.port < 1 || c.port > 65535)
    issues.push({ level: "error", message: "Port must be between 1 and 65535" });
  if (c.models.length === 0)
    issues.push({ level: "warning", message: "No data models — the schema will be empty" });

  const seen = new Set<string>();
  for (const model of c.models) {
    const name = pascalCase(model.name);
    if (seen.has(name))
      issues.push({ level: "error", message: `Duplicate model name "${name}"` });
    seen.add(name);

    const fieldNames = new Set<string>();
    for (const field of model.fields) {
      const fname = camelCase(field.name);
      if (["id", "updatedAt"].includes(fname))
        issues.push({
          level: "warning",
          message: `${name}.${fname} is generated automatically and will be ignored`,
        });
      if (fieldNames.has(fname))
        issues.push({
          level: "error",
          message: `Duplicate field "${fname}" on ${name}`,
        });
      fieldNames.add(fname);
    }
  }
  return issues;
}

export function estimateBytes(files: GeneratedFile[]): number {
  return files.reduce((sum, f) => sum + f.contents.length, 0);
}
